### ISSUE TITLE
Enums not being seeded when using multiple database providers

### ISSUE THREAD

**Issue by TAGC** [SpatialFocus/SpatialFocus.EntityFrameworkCore.Extensions#19]
When configuring a DbContext that sets up enums as part of the database schema, some part of this library seems to make it so that certain state or configuration is shared between DbContexts that are created using different providers. This can cause exceptions to get thrown when trying to ensure the database gets created when instantiating a DbContext using the second provider.

An example of this happening is practice is when running unit and integration tests together for an application. The unit tests might be configured to the `InMemory` provider, since no database behaviour needs to be simulated. On the other hand, integration tests might use the `SQLite` provider in order to more accurately reflect the behaviour of a relational database. If both sets of tests are run as part of the same test run, some of the tests may fail even though both sets pass when run independently of one another.

This only happens when the `ChangeTracker` property of the `DbContext` is accessed within its constructor.

### Code

To reproduce this issue, create a new C# console application targeting .NET 5 and include the code below. Add dependencies on these NuGet packages:

- `Microsoft.EntityFrameworkCore.InMemory`: 5.0.5
- `Microsoft.EntityFrameworkCore.Sqlite`: 5.0.5
- `SpatialFocus.EntityFrameworkCore.Extensions`: 2.1.2

#### Domain

```cs
public enum BlogType
{
    Unknown = 0,
    Private = 1,
    Public = 2
}

public class BlogTypeClass
{
    public int Id { get; init; }
    public string Description { get; init; }
}

public class Blog
{
    public int Id { get; init; }
    public BlogType BlogType { get; init; }
    public BlogTypeClass BlogTypeClass { get; init; }
}
```

#### Context

```cs
public class BloggingContext : DbContext
{
    // Issue only reproducible when both of these fields are set to "true".
    private static readonly bool AccessChangeTrackerInConstructor = true;

    private static readonly bool UseBlogTypeEnumInsteadOfClass = true;

    public BloggingContext(DbContextOptions options) : base(options)
    {
        if (AccessChangeTrackerInConstructor)
        {
            var _ = ChangeTracker.DebugView.ShortView;
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>(ConfigureBlog);

        if (UseBlogTypeEnumInsteadOfClass)
        {
            modelBuilder.ConfigureEnumLookup(EnumLookupOptions.Default.SetNamingScheme(x => x.Pascalize()));
        }
        else
        {
            modelBuilder.Entity<BlogTypeClass>(ConfigureBlogTypeClass);
        }

        SeedData(modelBuilder);
    }

    private static void ConfigureBlog(EntityTypeBuilder<Blog> builder)
    {
        builder.ToTable(nameof(Blog));
        builder.HasKey(b => b.Id);

        if (UseBlogTypeEnumInsteadOfClass)
        {
            builder.Ignore(b => b.BlogTypeClass);
        }
        else
        {
            builder.HasOne(b => b.BlogTypeClass).WithMany().HasForeignKey("BlogTypeId");
            builder.Ignore(b => b.BlogType);
        }
    }

    private static void ConfigureBlogTypeClass(EntityTypeBuilder<BlogTypeClass> builder)
    {
        builder.ToTable("BlogType");
        builder.HasKey(bt => bt.Id);
    }

    private static void SeedData(ModelBuilder modelBuilder)
    {
        if (UseBlogTypeEnumInsteadOfClass)
        {
            var blogs = new object[]
            {
                    new {Id = 1, BlogType = BlogType.Private},
                    new {Id = 2, BlogType = BlogType.Public}
            };

            modelBuilder.Entity<Blog>().HasData(blogs);
        }
        else
        {
            var blogTypes = new[]
            {
                    new BlogTypeClass {Id = 1, Description = "Private"},
                    new BlogTypeClass {Id = 2, Description = "Public"}
                };

            var blogs = new object[]
            {
                    new {Id = 1, BlogTypeId = 1},
                    new {Id = 2, BlogTypeId = 2}
            };

            modelBuilder.Entity<BlogTypeClass>().HasData(blogTypes);
            modelBuilder.Entity<Blog>().HasData(blogs);
        }
    }
}
```

#### Program

```cs

// Create a Context using InMemory provider.
var inMemoryOptions = new DbContextOptionsBuilder<BloggingContext>()
    .UseInMemoryDatabase(Guid.NewGuid().ToString())
    .Options;

// Issue only reproducible when line below is included
_ = new BloggingContext(inMemoryOptions);

// Create a Context using SQLite provider.
var sqliteOptions = new DbContextOptionsBuilder<BloggingContext>()
    .UseSqlite("Filename=:memory:")
    .Options;

var context = new BloggingContext(sqliteOptions);
context.Database.EnsureCreated();
```

### Expected Behaviour

Under all circumstances, this program runs without any exception being thrown.

### Actual Behaviour

When configuring this program to use enums via your library and to access the `ChangeTracker` in the `BloggingContext` constructor, the following exception gets thrown:

```
SQLite Error 19: 'FOREIGN KEY constraint failed'.
```

The exception has this stack trace:

```
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject) in /_/src/EFCore.Relational/Storage/RelationalCommand.cs:line 96
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues) in /_/src/EFCore.Relational/Migrations/MigrationCommand.cs:line 68
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection) in /_/src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs:line 52
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateTables() in /_/src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs:line 123
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated() in /_/src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs:line 243
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at <Program>$.<Main>$(String[] args) in C:\Projects\EfCoreMultipleProvidersIssue\Program.cs:line 21
```

Disabling "Just My Code", the execution can be traced to `Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery` where it tries to execute the command:

```sql
INSERT INTO "Blog" ("Id", "BlogType")
VALUES (1, 1);
```

Based on the exception being thrown, it appears that this library may not be seeding the enums if a DbContext is constructed using a second database provider within the same execution scope.

**Comment by Dresel** [comment]
Fixed by #20.

**Comment by pergerch** [comment]
We've created a new package version 2.1.3 which should fix your issue. Please have a look and thanks for your contribution.

**Comment by TAGC** [comment]
Excellent, cheers, that seems to have fixed the problem I was having in my application.
