### ISSUE TITLE
Support for .NET 8 / EFCore 8

### ISSUE THREAD

**Issue by bdbvb** [SpatialFocus/SpatialFocus.EntityFrameworkCore.Extensions#25]
I'm using the library for generating enum tables, but it looks like it doesn't work yet with .NET 8 / EFCore 8.

Error example:

...
System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<Microsoft.EntityFrameworkCore.Metadata.IMutableProperty> Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.GetProperties()'.
         at SpatialFocus.EntityFrameworkCore.Extensions.EnumLookupExtension.<>c.<ConfigureEnumLookup>b__0_0(IMutableEntityType x)
         at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
         at SpatialFocus.EntityFrameworkCore.Extensions.EnumLookupExtension.ConfigureEnumLookup(ModelBuilder modelBuilder, EnumLookupOptions enumOptions)
...

**Comment by av0** [comment]
I have created a pull request: https://github.com/SpatialFocus/EntityFrameworkCore.Extensions/pull/26

**Comment by pergerch** [comment]
Thank you @av0
.NET 8 Support is added in version 2.3 of the package

**Comment by Dresel** [comment]
Thanks @av0 for your contribution, your commits got merged and we have published a new version.
